[package]
name = "geo-bevy"
description = "Generate Bevy meshes from `geo` types"
version = "0.3.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2021"
repository = "https://github.com/frewsxcv/geo-bevy"
license = "MIT OR Apache-2.0"

[dependencies]
# TEMP: waiting for: https://github.com/frewsxcv/bevy-earcutr/pull/4 
bevy-earcutr ={ git = "https://github.com/gibbz00/bevy-earcutr" }
bevy = { version = "0.10", default-features = false,  features = ["bevy_render"] }
geo = "0.23"
